# Generated by Django 3.2.5 on 2022-10-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_System', '0003_alter_event_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClubUser',
            new_name='Employee',
        ),
    ]
